name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 0 * * *" # Genera l'immagine ogni giorno a mezzanotte
  workflow_dispatch: # Permette l'avvio manuale immediato

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A .
          git commit -m "Generated 3D Profile City" || exit 0
          git push
