name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 0 * * *" # Genera l'immagine ogni giorno a mezzanotte
  workflow_dispatch: # Permette l'avvio manuale immediato

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A .
          git diff --cached --quiet && exit 0
          git commit -m "Generated 3D Profile City"
          git push
